### ISSUE TITLE
OSError: [E050] Can't find model 'en_core_web_sm'

### ISSUE THREAD

**Issue by felsen** [DevopediaOrg/twitter-hashtag-selector#7]
While running flask server,

`python server.py`

Error Details:

```
Traceback (most recent call last):
  File "server.py", line 2, in <module>
    from utils.phraser import phrase_collector
  File "/home/felsen/Devopedia/twitter-hashtag-selector/tweetags/utils/phraser.py", line 3, in <module>
    sp = spacy.load('en_core_web_sm')
  File "/usr/local/lib/python3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/usr/local/lib/python3.7/site-packages/spacy/util.py", line 171, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by felsen** [comment]
The below command is solving the issue.
`python -m spacy download en`

**Comment by felsen** [comment]
So closing the issue.
